// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
	    int n = Integer.parseInt(args[0]);
		int big = 0;
		int small = 0;
		for (int i = 0 ; i < n ; i++){
			double randomNumber = Math.random();
			if (randomNumber > 0.5) {
				big ++;
			}else{
				small++;
			}
		}
		System.out.println(">0.5: " + big + " times");
		System.out.println("<=0.5" + small + "times");
		if (small > 0) {
			double ratio = big / small;
			System.out.println("Ratio:  " + ratio);
		}
	}
}
